services:
  app:
    image: h4kops/flask-notes-app:v1
    container_name: flask-notes-app-prod
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - notes-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: notes-postgres-db-prod
    env_file:
      - .env
    volumes:
      - notes-db-data:/var/lib/postgresql/data
    networks:
      - notes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notesuser -d notesdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  notes-db-data:

networks:
  notes-network:
    driver: bridge
