bankapp:
  replicaCount: 1

  image:
    tag: latest

  autoscaling:
    enabled: false

mysql:
  persistence:
    size: 2Gi
    storageClass: standard

ollama:
  persistence:
    size: 5Gi
    storageClass: standard
