apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pvc-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - sleep 3600

      volumeMounts:
        - name: dynamic-storage
          mountPath: /data

  volumes:
    - name: dynamic-storage
      persistentVolumeClaim:
        claimName: dynamic-pvc
